using System;

namespace Hurace.Core.Mapper.Attributes
{
    [AttributeUsage(AttributeTargets.Property)]
    public class Key : Attribute
    {
        public Key(bool autoGenerated = true)
        {
            this.AutoGenerated = autoGenerated;
        }

        public bool AutoGenerated { get; set; }
    }
}